const TERMINOLOGY = {
  healthcare: {
    person_employee:    "Caregiver",
    person_client:      "Client",
    person_plural:      "Care Team",
    product:            "Medication / Supply",
    product_plural:     "Medications & Supplies",
    address:            "Care Location",
    address_plural:     "Care Locations",
    service:            "Care Service",
    service_plural:     "Care Services",
    task:               "Care Task",
    task_plural:        "Care Tasks",
    transaction:        "Invoice",
    transaction_plural: "Invoices",
    objective:          "Care Outcome",
    enterprise_child:   "Care Facility",
  },
  education: {
    person_employee:    "Teacher / Staff",
    person_client:      "Student",
    person_plural:      "School Community",
    product:            "Learning Material",
    product_plural:     "Learning Materials",
    address:            "Campus / Classroom",
    address_plural:     "Campuses",
    service:            "Course / Program",
    service_plural:     "Courses & Programs",
    task:               "Lesson / Assignment",
    task_plural:        "Lessons & Assignments",
    transaction:        "Fee / Payment",
    transaction_plural: "Fees & Payments",
    objective:          "Learning Outcome",
    enterprise_child:   "School / Department",
  },
  community: {
    person_employee:    "Leader / Volunteer",
    person_client:      "Member",
    person_plural:      "Community",
    product:            "Resource / Material",
    product_plural:     "Resources",
    address:            "Meeting Place",
    address_plural:     "Meeting Places",
    service:            "Program / Ministry",
    service_plural:     "Programs",
    task:               "Activity / Event",
    task_plural:        "Activities & Events",
    transaction:        "Donation / Contribution",
    transaction_plural: "Contributions",
    objective:          "Community Goal",
    enterprise_child:   "Group / Chapter",
  },
  agriculture: {
    person_employee:    "Farm Hand / Vet",
    person_client:      "Animal / Crop Unit",
    person_plural:      "Farm Team",
    product:            "Feed / Medicine / Seed",
    product_plural:     "Farm Supplies",
    address:            "Barn / Field / Pen",
    address_plural:     "Farm Locations",
    service:            "Farm Service",
    service_plural:     "Farm Services",
    task:               "Farm Task",
    task_plural:        "Farm Tasks",
    transaction:        "Sale / Purchase",
    transaction_plural: "Farm Transactions",
    objective:          "Farm Goal",
    enterprise_child:   "Barn / Field",
  },
  business: {
    person_employee:    "Employee",
    person_client:      "Customer / Client",
    person_plural:      "Team",
    product:            "Product / Item",
    product_plural:     "Products & Inventory",
    address:            "Office / Location",
    address_plural:     "Locations",
    service:            "Service",
    service_plural:     "Services",
    task:               "Task",
    task_plural:        "Tasks",
    transaction:        "Invoice / Payment",
    transaction_plural: "Transactions",
    objective:          "Business Goal",
    enterprise_child:   "Department / Branch",
  },
  nonprofit: {
    person_employee:    "Staff / Volunteer",
    person_client:      "Beneficiary",
    person_plural:      "Organization",
    product:            "Supply / Resource",
    product_plural:     "Resources",
    address:            "Program Location",
    address_plural:     "Program Sites",
    service:            "Program / Service",
    service_plural:     "Programs",
    task:               "Activity",
    task_plural:        "Activities",
    transaction:        "Grant / Donation",
    transaction_plural: "Funding",
    objective:          "Impact Goal",
    enterprise_child:   "Program / Site",
  },
  government: {
    person_employee:    "Officer / Staff",
    person_client:      "Citizen / Constituent",
    person_plural:      "Department Staff",
    product:            "Asset / Equipment",
    product_plural:     "Assets",
    address:            "Office / District",
    address_plural:     "Districts",
    service:            "Public Service",
    service_plural:     "Public Services",
    task:               "Case / Action Item",
    task_plural:        "Cases",
    transaction:        "Budget Item",
    transaction_plural: "Budget",
    objective:          "Policy Goal",
    enterprise_child:   "Department / Unit",
  },
  other: {
    person_employee:    "Member / Staff",
    person_client:      "Participant",
    person_plural:      "People",
    product:            "Item",
    product_plural:     "Items",
    address:            "Location",
    address_plural:     "Locations",
    service:            "Service / Activity",
    service_plural:     "Services",
    task:               "Task",
    task_plural:        "Tasks",
    transaction:        "Transaction",
    transaction_plural: "Transactions",
    objective:          "Goal",
    enterprise_child:   "Sub-Enterprise",
  },
};

const TYPE_MAP = {
  healthcare:       "healthcare",
  home_health:      "healthcare",
  residential_care: "healthcare",
  skilled_nursing:  "healthcare",
  hospital:         "healthcare",
  clinic:           "healthcare",
  pharmacy:         "healthcare",
  mental_health:    "healthcare",
  veterinary:       "agriculture",
  education:        "education",
  school:           "education",
  university:       "education",
  training:         "education",
  tutoring:         "education",
  community:        "community",
  nonprofit:        "nonprofit",
  faith:            "community",
  church:           "community",
  mosque:           "community",
  temple:           "community",
  charity:          "nonprofit",
  ngo:              "nonprofit",
  social_services:  "nonprofit",
  agriculture:      "agriculture",
  farm:             "agriculture",
  livestock:        "agriculture",
  aquaculture:      "agriculture",
  retail:           "business",
  consulting:       "business",
  technology:       "business",
  manufacturing:    "business",
  logistics:        "business",
  hospitality:      "business",
  restaurant:       "business",
  hotel:            "business",
  professional:     "business",
  finance:          "business",
  construction:     "business",
  media:            "business",
  government:       "government",
  municipal:        "government",
  public_sector:    "government",
  other:            "other",
};

export function getTerms(category) {
  return TERMINOLOGY[category] || TERMINOLOGY.other;
}

export function getTermsFromEnterpriseType(type) {
  return TERMINOLOGY[TYPE_MAP[type]] || TERMINOLOGY.other;
}

export function getCategoryFromType(type) {
  return TYPE_MAP[type] || "other";
}

export function useTerm(enterpriseType, termKey) {
  return getTermsFromEnterpriseType(enterpriseType)[termKey] || termKey;
}

export default TERMINOLOGY;