# ==============================================================
# Newsconseen — Superset Configuration
# ==============================================================
# Placed at /app/pythonpath/superset_config.py inside the container.
# All sensitive values read from environment variables (Railway injects these).
# ==============================================================

import os

# ── Core security ──────────────────────────────────────────────────────────────
# REQUIRED: Set SECRET_KEY in Railway env vars.
# Generate one with: python -c "import secrets; print(secrets.token_hex(42))"
SECRET_KEY = os.environ.get("SUPERSET_SECRET_KEY", "CHANGE_ME_IN_RAILWAY_ENV_VARS")

# ── Database — Superset's own metadata store ───────────────────────────────────
# Superset needs its OWN PostgreSQL database for storing dashboards, charts,
# user accounts, etc.  This is SEPARATE from the Newsconseen analytics DB.
# Create a second Railway PostgreSQL service and set SUPERSET_DATABASE_URL.
SQLALCHEMY_DATABASE_URI = os.environ.get(
    "SUPERSET_DATABASE_URL",
    "sqlite:////app/superset.db",   # fallback for testing only
)

# ── Session / cache ────────────────────────────────────────────────────────────
# Use Redis if available (add Redis service in Railway).
# Falls back to in-memory if REDIS_URL not set — fine for small deployments.
_redis_url = os.environ.get("REDIS_URL", "")

if _redis_url:
    CACHE_CONFIG = {
        "CACHE_TYPE":             "RedisCache",
        "CACHE_DEFAULT_TIMEOUT":  300,
        "CACHE_KEY_PREFIX":       "superset_",
        "CACHE_REDIS_URL":        _redis_url,
    }
    DATA_CACHE_CONFIG = {
        "CACHE_TYPE":            "RedisCache",
        "CACHE_DEFAULT_TIMEOUT": 600,
        "CACHE_KEY_PREFIX":      "superset_data_",
        "CACHE_REDIS_URL":       _redis_url,
    }
    RESULTS_BACKEND = None   # use Redis for async results when Celery is wired
else:
    CACHE_CONFIG      = {"CACHE_TYPE": "SimpleCache", "CACHE_DEFAULT_TIMEOUT": 300}
    DATA_CACHE_CONFIG = {"CACHE_TYPE": "SimpleCache", "CACHE_DEFAULT_TIMEOUT": 600}

# ── Feature flags ──────────────────────────────────────────────────────────────
# EMBEDDED_SUPERSET: enables the guest token API used by SupersetEmbed.jsx
FEATURE_FLAGS = {
    "EMBEDDED_SUPERSET":             True,   # ← REQUIRED for Newsconseen embed
    "ENABLE_TEMPLATE_PROCESSING":    True,   # Jinja templating in SQL
    "DASHBOARD_NATIVE_FILTERS":      True,   # Native filter bar
    "DASHBOARD_CROSS_FILTERS":       True,   # Cross-chart filtering
    "ALERT_REPORTS":                 True,   # Scheduled alerts/reports
    "ROW_LEVEL_SECURITY":            True,   # ← REQUIRED for tenant isolation
    "ENABLE_EXPLORE_DRAG_AND_DROP":  True,
    "VERSIONED_EXPORT":              True,
}

# ── CORS — allow Newsconseen frontend to embed dashboards ──────────────────────
# Add your Base44 frontend domain here.
# If using a custom domain, add that too.
ENABLE_CORS = True

_frontend_origin = os.environ.get("NEWSCONSEEN_FRONTEND_URL", "*")

CORS_OPTIONS = {
    "supports_credentials": True,
    "allow_headers":        ["*"],
    "resources":            {"/api/*": {"origins": _frontend_origin}},
    "origins":              [_frontend_origin],
}

# ── Embedded dashboard — allowed domains ───────────────────────────────────────
# Domains allowed to embed Superset dashboards in iframes.
# Add your Railway frontend URL and any custom domain.
GUEST_ROLE_NAME    = "Gamma"   # role assigned to embedded guest users
GUEST_TOKEN_JWT_SECRET    = SECRET_KEY
GUEST_TOKEN_JWT_ALGO      = "HS256"
GUEST_TOKEN_HEADER_NAME   = "X-GuestToken"
GUEST_TOKEN_JWT_EXP_SECONDS = 300   # 5 minutes — short-lived for security

# Domains that can render Superset in an iframe
TALISMAN_CONFIG = {
    "frame_options":         "ALLOWFROM",
    "frame_options_allow_from": os.environ.get(
        "NEWSCONSEEN_FRONTEND_URL",
        "https://newsconseenwebapp-production.up.railway.app"
    ),
    "content_security_policy": False,   # relaxed for embedded mode
}

# ── Row Level Security filter table ───────────────────────────────────────────
# The guest token generated by /superset/guest-token in python_layer
# injects: WHERE company_id = '<company_id>'
# Superset enforces this on every query run inside the embedded dashboard.
# Make sure your Newsconseen data source tables ALL have a company_id column.

# ── Email / alerts (optional) ─────────────────────────────────────────────────
SMTP_HOST     = os.environ.get("SMTP_HOST", "")
SMTP_PORT     = int(os.environ.get("SMTP_PORT", "587"))
SMTP_STARTTLS = True
SMTP_SSL      = False
SMTP_USER     = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
SMTP_MAIL_FROM = os.environ.get("SMTP_FROM", "alerts@newsconseen.com")

# ── Misc ───────────────────────────────────────────────────────────────────────
ROW_LIMIT         = 50000     # max rows per chart query
SUPERSET_WEBSERVER_TIMEOUT = 60
WTF_CSRF_ENABLED  = True
WTF_CSRF_EXEMPT_LIST = [
    "superset.views.core.log",
    "superset.views.api",
]
SESSION_COOKIE_SAMESITE = "None"   # required for cross-origin iframe embedding
SESSION_COOKIE_SECURE   = True     # required with SameSite=None
SESSION_COOKIE_HTTPONLY = True

# ── Newsconseen data source connection string ──────────────────────────────────
# This is the Newsconseen analytics PostgreSQL (read-only recommended).
# Add this as a Database connection inside Superset UI after first login:
#   Sources → Databases → + → PostgreSQL
#   SQLAlchemy URI: value of NEWSCONSEEN_DB_URL below
NEWSCONSEEN_ANALYTICS_DB = os.environ.get(
    "NEWSCONSEEN_DB_URL",
    "",   # set this in Railway to your DATABASE_URL from python_layer
)
